<a href="https://colab.research.google.com/github/shubhamgupta7217/upskill/blob/main/pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series([1, 2, 3, np.nan])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [ ]:
dates = pd.date_range('20250715', periods=7)
dates

DatetimeIndex(['2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18',
               '2025-07-19', '2025-07-20', '2025-07-21'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(7, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-07-15  2.386886 -0.024837  0.940691 -1.446805
2025-07-16 -0.192552  1.993249 -0.165208  1.105207
2025-07-17  0.384822 -1.544070 -0.391045 -0.042488
2025-07-18  1.086935  1.692645  0.261005  0.894530
2025-07-19  0.036379  0.594551  1.417542 -0.700182
2025-07-20  0.169368  1.168351 -1.246780  0.097721
2025-07-21 -0.264921  0.754803  0.767267  0.971497

In [ ]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [ ]:
df.to_numpy()

array([[ 2.38688557, -0.02483705,  0.94069129, -1.44680515],
       [-0.19255214,  1.99324851, -0.16520797,  1.10520678],
       [ 0.38482173, -1.54407037, -0.39104458, -0.04248771],
       [ 1.08693502,  1.69264462,  0.26100546,  0.8945298 ],
       [ 0.03637929,  0.59455083,  1.41754229, -0.70018236],
       [ 0.16936753,  1.16835111, -1.24678015,  0.09772123],
       [-0.2649213 ,  0.754803  ,  0.76726651,  0.97149659]])

In [ ]:
df.describe()

              A         B         C         D
count  7.000000  7.000000  7.000000  7.000000
mean   0.515274  0.662099  0.226210  0.125640
std    0.940342  1.186205  0.906240  0.953050
min   -0.264921 -1.544070 -1.246780 -1.446805
25%   -0.078086  0.284857 -0.278126 -0.371335
50%    0.169368  0.754803  0.261005  0.097721
75%    0.735878  1.430498  0.853979  0.933013
max    2.386886  1.993249  1.417542  1.105207

In [ ]:
df.T

,2025-07-15,2025-07-16,2025-07-17,2025-07-18,2025-07-19,2025-07-20,2025-07-21
A,2.386886,-0.192552,0.384822,1.086935,0.036379,0.169368,-0.264921
B,-0.024837,1.993249,-1.544070,1.692645,0.594551,1.168351,0.754803
C,0.940691,-0.165208,-0.391045,0.261005,1.417542,-1.246780,0.767267
D,-1.446805,1.105207,-0.042488,0.894530,-0.700182,0.097721,0.971497

In [ ]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2025-07-15 -1.446805  0.940691 -0.024837  2.386886
2025-07-16  1.105207 -0.165208  1.993249 -0.192552
2025-07-17 -0.042488 -0.391045 -1.544070  0.384822
2025-07-18  0.894530  0.261005  1.692645  1.086935
2025-07-19 -0.700182  1.417542  0.594551  0.036379
2025-07-20  0.097721 -1.246780  1.168351  0.169368
2025-07-21  0.971497  0.767267  0.754803 -0.264921

In [ ]:
df.sort_values(by='B')

                   A         B         C         D
2025-07-17  0.384822 -1.544070 -0.391045 -0.042488
2025-07-15  2.386886 -0.024837  0.940691 -1.446805
2025-07-19  0.036379  0.594551  1.417542 -0.700182
2025-07-21 -0.264921  0.754803  0.767267  0.971497
2025-07-20  0.169368  1.168351 -1.246780  0.097721
2025-07-18  1.086935  1.692645  0.261005  0.894530
2025-07-16 -0.192552  1.993249 -0.165208  1.105207

In [ ]:
df['A']

2025-07-15    2.386886
2025-07-16   -0.192552
2025-07-17    0.384822
2025-07-18    1.086935
2025-07-19    0.036379
2025-07-20    0.169368
2025-07-21   -0.264921
Freq: D, Name: A, dtype: float64

In [ ]:
df.loc[dates[0]]

A    2.386886
B   -0.024837
C    0.940691
D   -1.446805
Name: 2025-07-15 00:00:00, dtype: float64

In [ ]:
dates

DatetimeIndex(['2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18',
               '2025-07-19', '2025-07-20', '2025-07-21'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.loc[dates[1]:,'B':]

                   B         C         D
2025-07-16  1.993249 -0.165208  1.105207
2025-07-17 -1.544070 -0.391045 -0.042488
2025-07-18  1.692645  0.261005  0.894530
2025-07-19  0.594551  1.417542 -0.700182
2025-07-20  1.168351 -1.246780  0.097721
2025-07-21  0.754803  0.767267  0.971497

In [ ]:
df.iloc[:5, 1:]

                   B         C         D
2025-07-15 -0.024837  0.940691 -1.446805
2025-07-16  1.993249 -0.165208  1.105207
2025-07-17 -1.544070 -0.391045 -0.042488
2025-07-18  1.692645  0.261005  0.894530
2025-07-19  0.594551  1.417542 -0.700182

In [ ]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]

In [ ]:
index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])
df

                     A         B
first second
bar   one     0.797372  1.161996
      two    -0.117606  0.558893
baz   one     0.133598  0.538143
      two     1.325510 -0.210079
foo   one     0.261162  0.006724
      two     0.270656 -1.181128
qux   one     1.040246  0.421508
      two    -0.841164  1.019171

In [ ]:
stacked = df.stack(future_stack=True)
stacked

first  second
bar    one     A    0.797372
               B    1.161996
       two     A   -0.117606
               B    0.558893
baz    one     A    0.133598
               B    0.538143
       two     A    1.325510
               B   -0.210079
foo    one     A    0.261162
               B    0.006724
       two     A    0.270656
               B   -1.181128
qux    one     A    1.040246
               B    0.421508
       two     A   -0.841164
               B    1.019171
dtype: float64

In [ ]:
stacked.unstack()

                     A         B
first second
bar   one     0.797372  1.161996
      two    -0.117606  0.558893
baz   one     0.133598  0.538143
      two     1.325510 -0.210079
foo   one     0.261162  0.006724
      two     0.270656 -1.181128
qux   one     1.040246  0.421508
      two    -0.841164  1.019171